### ISSUE TITLE
按翻譯就閃退

### ISSUE THREAD

**Issue by efklf3k3i3** [umichan0621/HighQuality-GalgameTranslator#2]
win10 x64 21h2 19044 繁中

按了就閃退

用py -m pip install -r requirements.txt 建構出來的也是一樣閃退

**Comment by umichan0621** [comment]
可能和python版本有关，近期会用其他语言重构项目

**Comment by efklf3k3i3** [comment]
非常感謝您的即時回覆
到時再來試試
